// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efzihbpaakvfnssmtpmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmemloYnBhYWt2Zm5zc210cG1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjY4NDgsImV4cCI6MjA2NzEwMjg0OH0.IhRCQU3GjwQ4nijr93RBjCJRbIurKGD06wSA82qvOSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});